app/source/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

app_name = "pengin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('pengin/', include('pengin.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/source/pengin/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *
from django.contrib import admin
from django.views import View

app_name = "pengin"
urlpatterns = [
    path("test/", testView, name='test'),
    path('signup/', signupDetaView, name='signup'),
    path('login/', loginDataView, name='login'),
    path('signup_check/', signupCheckView, name='signup_check'),
    path("product_registra/", ImageUploadView.as_view(), name='product_registra'),
    path('home/',HomeListView,name='home'),
    path('buyaddform/<int:number>/',BuyFormAddView,name='buyaddform'),
    path('buy_form/',messageView,name='buy_form'),
    path('product_registra/pengin/listing_complete',ListingCompleteView,name='listing_complete'),
    path('mypage/', mypageView, name='mypage'),
    path('update/', UserUpdateView.as_view(), name='update'),
    path('derete_check/', derete_check, name='derete_check'),
    path('search/', searchDateView, name='search'),
]

app/source/pengin/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, AbstractUser

class UserManager(BaseUserManager):
    def create_user(self, loginID, password=None):
        if not loginID:
            raise ValueError('Users must have an loginID address')

        user = self.model(
            loginID=self.normalize_email(loginID),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, loginID, password):
        user = self.create_user(
            loginID,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, loginID, password):
        user = self.create_user(
            loginID,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    class Meta:
        db_table = 'userScertification'

    name = models.CharField(max_length=500)
    loginID = models.CharField(max_length=20, unique=True)
    # Icon = models.ImageField(upload_to="images", default='/images/no_image_square.jpg', blank=True, null=True)
    createDate = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    # towns = ListCharField(
    #     models.CharField(max_length=10),size=6, max_length=(6 * 11))

    USERNAME_FIELD = 'loginID'
    objects = UserManager()

    def __str__(self):
        return self.loginID

    def has_perm(self, perm, obj=None):
        return self.admin

    def has_module_perms(self, app_label):
        return self.admin

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active


class ImageUpload(models.Model):
    class Meta:
        db_table = 'goods'
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    uniquename = models.CharField(max_length=100, unique=True)
    subject = models.CharField(max_length=500)
    price = models.IntegerField()
    mainimg = models.ImageField(upload_to="images")
    img1 = models.ImageField(upload_to="images", default='/images/no_image_square.jpg')
    img2 = models.ImageField(upload_to="images", default='/images/no_image_square.jpg')
    img3 = models.ImageField(upload_to="images", default='/images/no_image_square.jpg')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

# class Thread(models.Model):
#     goodsid = models.ForeignKey(ImageUpload, on_delete=models.CASCADE)
#     content  = models.TextField(blank=False, null=False)
#     user     = models.ForeignKey(User, on_delete=models.CASCADE)
#     created_datetime = models.DateTimeField(auto_now_add=True)
#     updated_datetime = models.DateTimeField(auto_now=True)
#     def __str__(self):
#         return self.title

class Comment(models.Model):
    comment = models.TextField(blank=False, null=False)
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    thread  = models.ForeignKey(ImageUpload, on_delete=models.CASCADE)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.comment
    

class IconUplodeModel(models.Model):
    class Meta:
        db_table = 'Icons'
    id = models.AutoField(primary_key=True)
    mainimg = models.ImageField(upload_to="images", default='/images/no_image_square.jpg')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

app/source/pengin/forms.py
from django import forms
from django.db import models
from .models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageUpload
        fields = {'name','subject','price','mainimg','img1','img2','img3'}
        labels = {'name':"商品名",'subject':'教科名','price':'価格','mainimg':"商品メインイメージ",'img1':"サブイメージ1",'img2':"サブイメージ2",'img3':"サブイメージ3"}

class LoginForm(AuthenticationForm):
    fields = ['loginID', 'password']
    labels = {'loginID':"ログインID",'password':"パスワード"}

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        print(model)
        # fields = "__all__"
        fields = ['name', 'loginID', 'password']
        labels = {'username': "ユーザーネーム",
                'loginID': "ログインID", 'password': "パスワード"}
        

# class LoginForm(AuthenticationForm):
#     class Meta:
#         fields = "__all__"

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = {'comment'}
        fields = {'comment': "コメント"}
        # fields = "__all__"

class IconForm(forms.ModelForm):
    class Meta:
        model = IconUplodeModel
        fields = {'mainimg': "アイコン"}

app/source/pengin/views.py
from django.shortcuts import render
from .models import User, ImageUpload,IconUplodeModel,Comment
from .forms import ImageUploadForm, UserForm, LoginForm, CommentForm,IconForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.shortcuts import render, redirect
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import string
import random
from django.contrib import messages
from django.db.models import Q

def testView(request):
    return render(request, 'pengin/test.html')

def signupDetaView(request):
    template_name = "pengin/signup.html"
    if request.method == "POST":  # フォームの入力を終えてすべてのフォームのデータともにviewに戻るとき
        form = UserForm(request.POST)  # ProfileFormを作る（？）

        print(form.is_valid())
        if form.is_valid():  # フォームの値が正しい時
            print('成功')
            question = form.save(commit=False)  # フォームを保存 ※commit=Falseでまだ保存しない
            # question.user = request.user
            # question = User(loginID = form.changed_data["loginID"])
            # question.Icon
            question.set_password(form.cleaned_data["password"])
            question.save()

            return render(request, 'pengin/signup_check.html', {})
    
    else: #初回アクセス時…空のフォームがほしいとき

        form = UserForm()

    return render(request, 'pengin/signup.html', {"user_form": form})

def loginDataView(request):
    print('request.method == POST')
    print(request.method)
    # ↑GET
    if request.method == 'POST':
        next = request.POST.get('next')
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            print('成功')
            user = form.get_user()
            if user:
                login(request, user)
            return redirect('pengin:home')
            # return render(request, 'pengin/home.html', {})
        else:
            print('そんな値はないです')
            for ele in form :
                print(ele)
    else:
        form = LoginForm()

    return render(request, 'pengin/login.html', {'form': form})

def signupCheckView(request):
    return render(request, 'pengin/signup_check.html')

# @login_required
class ImageUploadView(View):
    template_name = 'pengin/product_registra.html'

    def get(self, request):
        form = ImageUploadForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ImageUploadForm(request.POST, request.FILES)
        nowuser = request.user
        def generate_random_string(length):
            characters = string.ascii_letters
            return ''.join(random.choice(characters) for _ in range(length))

        random_string = generate_random_string(8)
        print(random_string)

        if form.is_valid():
            image_upload = form.save(commit=False)
            image_upload.user = request.user
            image_upload.uniquename = random_string
            image_upload.save()
            return redirect('pengin/listing_complete')
        return render(request, self.template_name, {'form': form})
@login_required
def HomeListView(request):
    template_name = "pengin/home.html"
    result_url = "pengin/buy_form/"
    sample_users = User.objects.values('id', 'name')
    img_list = ImageUpload.objects.values('id','name','subject','price','mainimg','img1','img2','img3','user')
    context = {
        'users': sample_users,
        'images': img_list,
    }
    
    # print(sample_users)
    # print(request.method)
    if request.method == 'POST':
        for img in img_list:
            name = img.get('name')
            nowID = img.get('id')
            # print(name)
            if name in request.POST:
                print('ボタン押されたで')
                print(type(nowID))
                # return render()
                # result = f"/pengin/buy_form/{nowID}"
                # return redirect(result)
                # url = reverse('BuyFormView', kwargs={'number': nowID})
                # return HttpResponseRedirect(url)
    return render(request, template_name, context)
@login_required
def ListingCompleteView(request):
    template_name = "pengin/listing_complete.html"
    return render(request,template_name)
@login_required
def BuyFormView(request):
    template_name = "pengin:buy_form"
    form = CommentForm
    sample_users = User.objects.values('id', 'name')
    img_list = ImageUpload.objects.values('id','name','mainimg','img1','img2','img3','user')
    context = {
        'form':form,
        'users': sample_users,
        'images': img_list,
    }
    print(sample_users)

    return render(request, template_name, context)
@login_required
def BuyFormAddView(request, number):
    template_name = "pengin/buy_form.html"
    form = CommentForm
    img_list = ImageUpload.objects.values('id','name','uniquename', 'subject', 'price','mainimg','img1','img2','img3','user')
    comment = Comment.objects.values('comment', 'user', 'thread')
    user = User.objects.values('id', 'name', 'loginID', 'createDate', 'active', 'staff', 'admin')
    # print("~~~~~~~~~~~")
    # print(comment)
    # print("--")
    # print(user)
    # print("~~~~~~~~~~~")
    context = {
        'number':number,
        'form': form,
        'image': img_list,
        'comment': comment,
        'user': user
    }
    return render(request, template_name, context)
@login_required
def messageView(request):
    # template_name = "pengin:buy_form"
    template_name = "pengin:buyaddform"
    number = request.POST['number']
    print(number)

    form = CommentForm(data=request.POST)

    # if request.method == "POST":  # フォームの入力を終えてすべてのフォームのデータともにviewに戻るとき
    #     form = UserForm(request.POST)  # ProfileFormを作る（？）

    print(form.is_valid())

    if form.is_valid():  # フォームの値が正しい時
        print('成功')
        comment = form.save(commit=False)
        print(request.user)
        comment.user = request.user
        thread_number = ImageUpload.objects.get(id=number) 
        comment.thread = thread_number
        comment.save()
        print(thread_number)

        return redirect(template_name, number=number)
       
        # return render(request, template_name, context)

    else: #初回アクセス時…空のフォームがほしいとき
        #フォーム作成
        context = {
            'form': form,
        }
        return render(request, template_name, context)


# def display_comments(request, thread_id):
#     #該当する掲示板一件を取得
#     threads = Thread.objects.filter(pk=thread_id).values()
#     thread  = threads[0]
#     username_dicts = User.objects.filter(pk=threads[0]['user_id']).values('username')
#     thread.update(username_dicts[0])
#     #該当する掲示板に紐づくコメントを取得
#     comments = Comment.objects.filter(thread_id=thread_id).values()
#     count = len(comments)
#     #コメントのユーザーIDからユーザー名を取得してオブジェクトに追加
#     for count in range(count):
#         username_dicts = User.objects.filter(pk=comments[count]['user_id']).values('username')
#         comments[count].update(username_dicts[0])
#     #フォーム作成
#     form = CommentForm()
#     context = {
#         'thread': thread,
#         'comments': comments,
#         'form': form,
#     }
#     return render(request, 'pengin/buy_form.html', context)
@login_required
def mypageView(request):
    sample_users = User.objects.values('id','name','loginID')
    img_list = ImageUpload.objects.values('id','name','uniquename','mainimg','img1','img2','img3','user')
    icon_list = IconUplodeModel.objects.values('id','mainimg','user')
    

    context = {
        'img_list':img_list,
        'user_list':sample_users,
        'icon_list':icon_list,
    }
    
    myuser = request.user
    myuser = str(myuser)
    myuserID = ''
    for user in sample_users:
        # print(type(user.get('loginID')))
        # print(user.get('loginID'))
        # print(type(myuser))
        # print(myuser)
        if user.get('loginID') == myuser:
            myuserID=user.get('id')
            context['ID'] = myuserID
    
    if request.method == 'POST':
        for img in img_list:
            uniquename = img.get('uniquename')
            print(uniquename)
            nowID = img.get('id')
            print(nowID)
            # print(name)
            if uniquename in request.POST:
                print('ボタン押されたで')
                print(type(nowID))
                ImageUpload.objects.get(id=nowID).delete()

                img_list = ImageUpload.objects.values('id','name','uniquename','mainimg','img1','img2','img3','user')
                context = {
                    'img_list':img_list,
                }

                # return render()
                # result = f"/pengin/buy_form/{nowID}"
                # return redirect('mypage')
                # url = reverse('mypage')
                # return HttpResponseRedirect(url)
                return render(request, 'pengin/dereteCheck.html')
    
    return render(request, 'pengin/mypage.html',context)

# @login_required
class UserUpdateView(View):
    template_name = 'pengin/Userdataupdate.html'

    def get(self, request):
        form = IconForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = IconForm(request.POST, request.FILES)
        nowuser = request.user

        icon = IconUplodeModel.objects.filter(user=request.user).first()
        if icon:
            icon.delete()

        if form.is_valid():
            icon = form.save(commit=False)
            icon.user = request.user
            icon.save()
            return redirect('pengin:mypage')
        return render(request, self.template_name, {'form': form})


def derete_check(request):
    return render(request, 'pengin/dereteCheck.html')

def searchDateView(request):
    image = ImageUpload.objects.order_by('-id')
    """ 検索機能の処理 """
    keyword = request.GET.get('keyword')

    if keyword:

app/source/pengin/templates/pengin/Userdataupdate.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test</title>
    <!-- <link href="{% static '/favicon.ico' %}" rel="icon"> -->
    <link rel="stylesheet" href="{% static 'css/Userdataupdate.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
</head>

<body>
    <header>
        <h1><img src="/media_local/images/logo.png" alt="">
            <form method="get" action="#" class="search_container">
            </form>
        </h1>
        <ul class="head">
            <a href="">
                <li>マイページ</li>
            </a>
            <a href="{% url 'pengin:product_registra' %}" class="log">
                <li class="syu">出 品</li>
            </a>
        </ul>
    </header>
    <div class="container">
        <div class="form-container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>画像アップロード</p>
                <div class="upload-container">
                    {{ form }}
                  </div>
                <p class="botton"><input type="submit" class="login-botton" value="登録"></p>
            </form>
        </div>
    </div>
</body>

</html>

app/source/pengin/templates/pengin/buy_form.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>詳細</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/buy_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'css/buy_form.js' %}"></script>
</head>


<body>
    <header>
        <h1>
            
            <a href="{% url 'pengin:home' %}">
                <img src="/media_local/images/logo.png" alt="">
              </a>
          
        </h1>
        <ul class="head">
            <a href="{% url 'pengin:mypage' %}">
                <li>マイページ</li>
            </a>
            <a href="{% url 'pengin:product_registra' %}" class="log">
                <li class="syu">出品</li>
            </a>
            
        </ul>
    </header>
    
    <div class="product-details">
       
        
        <div class="sub-images">
            {% for img in image %}
            {% if number == img.id %}
            <img src="/media_local/{{img.mainimg}}" name="{{img.name}}" class="rounded-pill sub-img" alt="送信">
            <img src="/media_local/{{img.img1}}" name="{{img.name}}" class="rounded-pill sub-img" alt="送信">
            <img src="/media_local/{{img.img2}}" name="{{img.name}}" class="rounded-pill sub-img" alt="送信">
            <img src="/media_local/{{img.img3}}" name="{{img.name}}" class="rounded-pill sub-img" alt="送信">
            {% endif %}
            {% endfor %}
        </div>
        <div class="image-container">
            {% for img in image %}
            {% if number == img.id %}
            <img src="/media_local/{{img.mainimg}}" name="{{img.name}}" class="rounded-pill main-img" alt="送信">
            {% endif %}
            {% endfor %}
        </div>

        <div class="details">
            {% for img in image %}
            {% if img.id == number %}
            <div class="info-container">
                <p class="img-name">{{ img.name }}</p>
                <p class="img-price">¥ {{ img.price }}</p>
                <p class="comments-title">商品詳細</p>
                <p class="img-subject">{{ img.subject }}</p>
            </div>
            {% endif %}
            {% endfor %}

            <div class="comments">
                <p class="comments-title">商品へのコメント</p>
                {% for com in comment %}
                {% if com.thread == number %}
                <div class="comment">
                    {% for us in user %}
                    {% if com.user == us.id %}
                    <p class="username">{{ us.name }}</p>
                    <p class="usercomment">{{ com.comment }}</p>
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                {% endfor %}
            </div>

            <form method="post" action="{% url 'pengin:buy_form' %}">
                <input type="hidden" value="{{ number }}" name="number">
                {% csrf_token %}
                {{ form.comment }}
                <button type="submit" class="positive_button">コメントを送信する</button>
                <!-- </form> -->
            
            
    </div>

</body>

</html>

app/source/pengin/templates/pengin/home.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/homes.css' %}">
</head>

<body>
    <header>
        <h1><img src="/media_local/images/logo.png" alt="">
            <form method="GET" action="{% url 'pengin:search' %}">
                <input type="text" name="keyword" placeholder=" キーワード検索" style="width:250px;height:38px;">
                <button type="submit" style="width:55px;height:40px;">検索</button>
            </form>
        </h1>
        <ul class="head">
            <a href="{% url 'pengin:home' %}" class="log">
                <li>ホーム</li>
            </a>
            <a href="{% url 'pengin:login' %}">
                <li>ログアウト</li>
            </a>
            <a href="{% url 'pengin:mypage' %}">
                <li>マイページ</li>
            </a>
            <a href="{% url 'pengin:product_registra' %}" class="log">
                <li class="syu">出 品</li>
            </a>
        </ul>
    </header>

    <div class="sen"></div>

    <!--ホームの表示-->
    <form method="post">
        {% csrf_token %}
        <div class="box">
            {% for img in images %}
            <div class="wapper-home">
                <a href="{% url 'pengin:buyaddform' img.id %}"> <!--商品の画像-->
                    <p class="name">{{img.name}}<!--商品の名前--></p>
                    <p class="price">￥{{img.price}}</p>
                    <img src="/media_local/{{img.mainimg}}" name="{{img.name}}" class="rounded-pill" width="50"
                        height="50" class="border_radius" alt="送信" />
                </a>
            </div>
            {% endfor %}
        </div>
    </form>

    <!--検索結果の表示-->
    <div class="box">
        {% for img in image %}
        <div class="wapper-home">
            <a href="{% url 'pengin:buyaddform' img.id %}"> <!--商品の画像-->
                <p class="name">{{img.name}}<!--商品の名前--></p>
                <p class="price">￥{{img.price}}</p>
                <img src="/media_local/{{img.mainimg}}" name="{{img.name}}" class="rounded-pill" width="50" height="50"
                    class="border_radius" alt="送信" />
            </a>
        </div>
        {% endfor %}
    </div>

</body>

</html>

app/source/pengin/templates/pengin/listing_complete.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/listing.css' %}">
</head>

<body>
    <header>
        <h1><img src="/media_local/images/logo.png" alt="">
            <form method="get" action="#" class="search_container">
                <input type="text" size="35" placeholder=" キーワード検索"><input type="submit" value="検索">
            </form>
        </h1>
        <ul class="head">
            <a href="{% url 'pengin:product_registra' %}">
                <li>マイページ</li>
            </a>
            <a href="{% url 'pengin:product_registra' %}" class="log">
                <li class="syu">出品</li>
            </a>
        </ul>
    </header>
    <div class="wapp">
        <h1 class="top">出品が完了しました！</h1>
        <p class="item"><a href="{% url 'pengin:product_registra' %}" class="it1">続けて出品する</a></p>
        <p class="item"><a href="{% url 'pengin:home' %}" class="it2">ホームへ</a></p>
        <p><a href="{% url 'pengin:mypage' %}" class="item2">マイページを見る</a></p>
    </div>
</body>

</html>

app/source/pengin/templates/pengin/login.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
</head>

<body>
    <header>
        <h1><img src="/media_local/images/logo.png" alt="">
    </header>
    <div class="pt-4">
        <h1 class="login-name">ログイン</h1>
        <form action="{% url 'pengin:login' %}" method="POST">
            {% csrf_token %}
            <p><input type="hidden" name="next" value="{{next}}"></p>
            <!--{{ form.as_p }}-->
            <p>UserID</p>
            {{ form.username }}
            <p>Password</p>
            {{form.password}}
            <p class="botton"><input type="submit" value="LOGIN" class="login-botton"></p>
        </form>
        <p class="sinki"><a href="{% url 'pengin:signup' %}">新規登録はこちら</a></p>
        {{ form.management_form }}
    </div>
</body>

</html>

app/source/pengin/templates/pengin/mypage.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test</title>
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}">
</head>

<body>
    <header>
        <h1><a href="{% url 'pengin:home' %}">
            <img src="/media_local/images/logo.png" alt="">
          </a>
            <form method="get" action="#" class="search_container">

            </form>
        </h1>
       
        <ul class="head">
            <a href="{% url 'pengin:home' %}" class="log">
                <li>ホーム</li>
            </a>
            <a href="{% url 'pengin:login' %}">
                <li>ログアウト</li>
            </a>
            <a href="{% url 'pengin:product_registra' %}" class="log">
                <li class="syu">出 品</li>
            </a>
        </ul>
    </header>
    <form method="post" action="{% url 'pengin:mypage' %}">
        {% csrf_token %}

        <div class="container">

    <div class="user-info">
      <!-- ここからユーザーアイコンの表示 -->
      {% for icon in icon_list %}
      {% if icon.user == ID %}
      <div class="avatar">
        <img src="/media_local/{{icon.mainimg}}" class="rounded-pill" width="70">
      </div>
      <div class="username">{{ user.name }}</div>
      {% else %}
      {% endif %}
      {% endfor %}
    </div>
    <div class="avatar-update">
      <a href="{% url 'pengin:update' %}">アイコンの変更</a>
    </div>
    <div class="product-list">
      <!-- ここからユーザー商品情報の表示 -->
      {% for img in img_list %}
      {% if img.user == ID %}
      <div class="product-info">
        <div class="image-container">
            <a href="{% url 'pengin:buyaddform' img.id %}"> <!--商品の画像-->
          <img src="/media_local/{{ img.mainimg }}" class="rounded-pill" width="50">
        </div></a>
        <div class="img-name">{{ img.name }}</div> <!-- img-nameを画像の下に表示 -->
    
        <button class="btn btn-outline-secondary rounded-pill btn-sm" type="submit" id="{{ img.id }}" name="{{ img.uniquename }}">削除</button>
      </div>
      {% else %}
      {% endif %}
      {% endfor %}
      </div>
  </div>

    </form>
    
</body>

</html>

app/source/pengin/templates/pengin/signup.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
</head>

<body>
    <header>
        <h1><img src="/media_local/images/logo.png" alt="">
    </header>
    <div class="pt-4">
        <h1 class="login-name">ユーザー登録</h1>
        <form action="{% url 'pengin:signup' %}" method="post">
            {% csrf_token %}
            <!-- {{ user_form.as_p }} 'name', 'loginID', 'password'-->
            <p>Name</p>
            {{ user_form.name }}
            <p>LoginID</p>
            {{ user_form.loginID }}
            <p>Password</p>
            {{ user_form.password }}
            <p class="botton"><input type="submit" class="login-botton" value="登録"></p>
        </form>
    </div>
    {% if user_form.errors %}
        <p>エラーメッセージ</p>
        <ul>
            {% for field in user_form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}
</body>

</html>